### ISSUE TITLE
Cannot connect

### ISSUE THREAD

**Issue by aldenis** [vanicat/hubic-swift#10]
hubic-swift worked flawlessly. Since today, I get the following error:

```
$ ./hubic-swift  stat
/usr/lib/ruby/vendor_ruby/mechanize/http/agent.rb:268:in `fetch': 509 =>  (Mechanize::ResponseCodeError)
        from /usr/lib/ruby/vendor_ruby/mechanize.rb:1182:in `post_form'
        from /usr/lib/ruby/vendor_ruby/mechanize.rb:515:in `submit'
        from /usr/lib/ruby/vendor_ruby/mechanize/form.rb:178:in `submit'
        from /usr/lib/ruby/vendor_ruby/mechanize/form.rb:184:in `click_button'
        from /soft/local/src/hubic/hubic-swift:172:in `connect_to_hubic'
        from /soft/local/src/hubic/hubic-swift:243:in `main'
        from /soft/local/src/hubic/hubic-swift:251:in `<main>'
```

My system is up to date Debian stable.
Thanks!

**Comment by aldenis** [comment]
Oops. Looks like it is duplicate with bug #9
